### ISSUE TITLE
Implement scylladb store for new indexer

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#1]
Description
------------------------
As Carbonable I should be able to implement scylladb store for new indexer
inorder to fast key value store database.

In a file located at `internal/storage/scylladb.go` implement interface *Storage* located in [storage.go](../blob/main/internal/storage/storage.go) to enable scylladb usage as a database

Additional Information
---------------------------
[Medium Difficulty  - Go - High Priority]

Acceptance Criteria
-------------------------
- [ ]  scylladb store for new indexer

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by LuisDi98** [comment]
I'd like to take this one
