### ISSUE TITLE
Centralized Indexer Configuration

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#18]
Description
--------------------------
As Carbonable we will have 1 centralized Indexer which will send config files instead of creating many small indexers
in order to make the indexer work more centralized and decoupled.

Acceptance Criteria
--------------------------------
 - [ ] Enable to have 1 indexer for all of our applications

**Comment by fishonamos** [comment]
Hi @MartianGreed. I can handle this. Though I may need additional details. I will talk to you on Telegram.
