### ISSUE TITLE
Implement rabbitMQ message bus

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#2]
Description
------------------------
As Carbonable I should be able to implement rabbitMQ message bus
inorder to stream data to our users

In a file located at `internal/dispatcher/rabbitmq.go` implement interface *EventDispatcher* located in [dispatcher.go](../blob/main/internal/dispatcher/dispatcher.go) 

Additional Information
---------------------------
[Medium Difficulty  - Go - Normal Priority]

Acceptance Criteria
-------------------------
- [ ]  rabbitMQ message bus

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by TropicalDog17** [comment]
Hi, may I work on this issue?

**Comment by TropicalDog17** [comment]
Hi, due to lack of time I would like to be unassigned of this issue. Thank for your understanding

**Comment by piavgh** [comment]
just asked on Telegram group (username @h8h_0x)
If there is no one took this issue yet, I would love to work on it
