### ISSUE TITLE
Implement nats.io message bus

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#3]
Description
------------------------
As Carbonable I should be able to implement nats.io message bus
inorder to stream data to our users

In a file located at `internal/dispatcher/nats.go` implement interface *EventDispatcher* located in [dispatcher.go](../blob/main/internal/dispatcher/dispatcher.go) 

Additional Information
---------------------------
[Medium Difficulty  - Go - Medium Priority]

Acceptance Criteria
-------------------------
- [ ]  nats.io message bus

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by joaquinbarrientoscr** [comment]
I'm interested in contributing to this issue :)
