### ISSUE TITLE
Implement one click aws deployment

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#4]
Description
------------------------
As Carbonable I should be able to implement one click aws deployment
inorder to achieve solution in deploying in one click

Implement required infrastructure using proprietary [Cloud Formation](https://docs.aws.amazon.com/cloudformation/)

Additional Information
---------------------------
[High Difficulty  - Go - Low Priority]

Acceptance Criteria
-------------------------
- [ ]  one click aws deployment

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by AryanGodara** [comment]
@MartianGreed Can you please assign me this issue :D
