### ISSUE TITLE
Implement datasource switch (switch from feeder gateway to rpc full node)

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#6]
Description
------------------------
As Carbonable I should be able to Implement datasource switch (switch from feeder gateway to rpc full node)

You can improve command line arguments to add flag either to use feeder gateway or full node as datasource 

Additional Information
---------------------------
[High Difficulty  - Go - Medium Priority]

Acceptance Criteria
-------------------------
- [ ] Implement datasource switch

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by joaquinbarrientoscr** [comment]
Interested in this one!

**Comment by MartianGreed** [comment]
resolved by #14
