### ISSUE TITLE
Implement RPC load balancer forwarding

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#7]
Description
------------------------
As Carbonable I should be able to implement RPC load balancer forwarding using [Nori](https://github.com/keep-starknet-strange/nori).

To enable rpc like feature, you could also implement Nori. (Very exciting feature imo)

Additional Information
---------------------------
[Medium Difficulty  - Go - Low Priority]

Acceptance Criteria
-------------------------
- [ ] Implement RPC load balancer forwarding
- [ ] Use feature flag or command arg to use this as the rpc provider

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by AryanGodara** [comment]
@MartianGreed Can you please assign this one to me, I've introduced myself on the telegram group :D
