### ISSUE TITLE
Use indexer as rpc

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#8]
Description
------------------------
As Carbonable I should be able to use indexer as rpc
because we store some data, we may want to impl starknet_rpc specs to provide an rpc access for whoever wants to deploy an indexer

Additional Information
---------------------------
[very Difficulty  - Go - low Priority]

Acceptance Criteria
-------------------------
- [ ] Use indexer as rpc

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by fishonamos** [comment]
@tekkac Can this be assignd to me?

**Comment by Khyati729** [comment]
@fishonamos would you like to start working on this? 
If yes, kindly please

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself 
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by fishonamos** [comment]
Hi @Khyati729 @MartianGreed   I will love to start up on this!
