### ISSUE TITLE
Integrate juno to indexer and use it as datasource

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/indexer#9]
Description
------------------------
As Carbonable I should be able to integrate juno to indexer and use it as datasource. 

[Juno](https://github.com/nethermindEth/juno) is an open source full node develop in go. As we use the same language we can use juno as a dependency package to replace internal indexer fetching data.

Additional Information
---------------------------
[very Difficult  - Go - low Priority]

Acceptance Criteria
-------------------------
- [ ] Integrate juno to indexer
- [ ] Use juno database or internal api as data source for block fetching
- [ ] Add the option to use or not juno as the main datasource / datafetcher

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by fishonamos** [comment]
Hi @tekkac @Khyati729 Can I be assigned to this?
